spring:
server:
  port: 7000
zuul:
  routes:
    serv-habitaciones:
      path: /shabitaciones/**
      serviceId: servicio-habitaciones
    serv-hoteles:
      path: /shoteles/**
      serviceId: servicio-hoteles
    serv-reservas:
      path: /sreservas/**
      serviceId: servicio-reservas
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka
